"""Shared tick constants for Zone Stalkers world simulation."""

from __future__ import annotations

HUNGER_INCREASE_PER_HOUR = 3
THIRST_INCREASE_PER_HOUR = 5
SLEEPINESS_INCREASE_PER_HOUR = 4

CRITICAL_THIRST_THRESHOLD = 80
CRITICAL_HUNGER_THRESHOLD = 80
CRITICAL_HP_THRESHOLD = 30

HP_DAMAGE_PER_HOUR_CRITICAL_THIRST = 2
HP_DAMAGE_PER_HOUR_CRITICAL_HUNGER = 1

BRAIN_TRACE_MAX_EVENTS = 5
