# Strategic
STRATEGIC_MAP_WIDTH = 10
STRATEGIC_MAP_HEIGHT = 10
INITIAL_GROUPS_PER_SIDE = 2
GROUP_HP_POOL = 30
GROUP_MOVE_RANGE = 1
GROUP_UNITS_ON_DEPLOY = 3
RESOURCE_NODES_COUNT = 4
TERRAIN_TYPES = ["plain", "forest", "ruins"]

# Tactical
TACTICAL_MAP_WIDTH = 8
TACTICAL_MAP_HEIGHT = 8
UNITS_PER_GROUP = 3
UNIT_HP = 10
UNIT_DAMAGE = 4
UNIT_MOVE_RANGE = 3
UNIT_ATTACK_RANGE = 3
UNIT_INITIATIVE = 10
COVER_DAMAGE_REDUCTION = 1
OBSTACLES_MIN = 4
OBSTACLES_MAX = 8
COVER_CELLS_MIN = 2
COVER_CELLS_MAX = 4

WIN_ALL_GROUPS_DESTROYED = "all_groups_destroyed"
WIN_RESOURCE_CONTROL = "resource_control"
