import React from 'react';

// ─── Styles shared across DebugMapPage and its sub-components ─────────────────

export const s: Record<string, React.CSSProperties> = {
  page: {
    display: 'grid',
    gridTemplateColumns: 'minmax(520px, 1fr) minmax(420px, 520px)',
    gap: 12,
    alignItems: 'flex-start',
    minHeight: 500,
    minWidth: 0,
  },
  canvasWrap: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
    minWidth: 0,
  },
  toolbar: {
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
    padding: '6px 10px',
    background: '#060b14',
    borderRadius: 8,
    border: '1px solid #1e293b',
  },
  toolbarRow1: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
  },
  toolbarRow2: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    flexWrap: 'wrap',
  },
  toolbarGroup: {
    display: 'flex',
    alignItems: 'center',
    gap: 4,
  },
  toolbarSep: {
    width: 1,
    height: 22,
    background: '#1e293b',
    flexShrink: 0,
  },
  zoomGroup: {
    display: 'flex',
    alignItems: 'center',
  },
  zoomBtn: {
    borderRadius: 7,
    padding: '0.25rem 0.4rem',
    minWidth: 26,
    textAlign: 'center' as const,
  },
  legend: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '6px 14px',
  },
  legendItem: {
    display: 'flex',
    alignItems: 'center',
    gap: 5,
    color: '#475569',
    fontSize: '0.68rem',
  },
  legendDot: {
    width: 8,
    height: 8,
    borderRadius: '50%',
    flexShrink: 0,
  },
  toolBtn: {
    padding: '0.25rem 0.65rem',
    background: '#0f172a',
    color: '#94a3b8',
    border: '1px solid #334155',
    borderRadius: 7,
    cursor: 'pointer',
    fontSize: '0.72rem',
    fontWeight: 600,
  },
  toolBtnActive: {
    background: '#1c2a1a',
    color: '#86efac',
    borderColor: '#22c55e',
  },
  linkHint: {
    background: '#0d1a0d',
    border: '1px solid #166534',
    borderRadius: 7,
    padding: '0.35rem 0.7rem',
    color: '#86efac',
    fontSize: '0.75rem',
  },
  canvasScroll: {
    position: 'relative',
    overflow: 'hidden',
    background: '#060b14',
    borderRadius: 10,
    border: '1px solid #1e293b',
    height: 'min(620px, 72vh)',
  },
  detailPanel: {
    minWidth: 420,
    maxWidth: 560,
    minHeight: 0,
    overflowX: 'hidden',
  },
  detail: {
    background: '#0f172a',
    borderRadius: 10,
    border: '1px solid #334155',
    padding: '1rem',
    display: 'flex',
    flexDirection: 'column',
    gap: '0.75rem',
    maxHeight: '72vh',
    overflowY: 'auto',
    overflowX: 'hidden',
    minWidth: 0,
    wordBreak: 'break-word',
    overflowWrap: 'anywhere',
  },
  detailHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 8,
    minWidth: 0,
  },
  detailName: {
    color: '#f8fafc',
    fontWeight: 700,
    fontSize: '1rem',
    wordBreak: 'break-word',
    overflowWrap: 'anywhere',
  },
  detailMeta: {
    color: '#475569',
    fontSize: '0.72rem',
    marginTop: 2,
  },
  closeBtn: {
    background: 'transparent',
    border: 'none',
    color: '#64748b',
    cursor: 'pointer',
    fontSize: '1rem',
    padding: '0.15rem',
    lineHeight: 1,
    flexShrink: 0,
  },
  connDelBtn: {
    background: 'transparent',
    border: 'none',
    color: '#475569',
    cursor: 'pointer',
    fontSize: '0.7rem',
    padding: '0 0.2rem',
    lineHeight: 1,
    flexShrink: 0,
  },
  emptyDetail: {
    background: '#0f172a',
    borderRadius: 10,
    border: '1px solid #1e293b',
    padding: '1rem',
    color: '#475569',
    fontSize: '0.82rem',
    minWidth: 0,
  },
  emptyDetailTitle: {
    color: '#475569',
    fontWeight: 700,
    fontSize: '0.72rem',
    textTransform: 'uppercase',
    letterSpacing: '0.06em',
    marginBottom: 8,
  },
  emptyDetailHint: {
    margin: 0,
    lineHeight: 1.5,
  },
  hr: {
    borderColor: '#1e293b',
    margin: '10px 0',
  },
  editBtn: {
    background: '#1e3a5f',
    border: '1px solid #3b82f6',
    color: '#93c5fd',
    cursor: 'pointer',
    fontSize: '0.68rem',
    padding: '0.15rem 0.4rem',
    borderRadius: 4,
    lineHeight: 1.4,
    flexShrink: 0,
  },
  editDetailBtn: {
    background: '#1e3a5f',
    border: '1px solid #3b82f6',
    color: '#93c5fd',
    cursor: 'pointer',
    fontSize: '0.72rem',
    padding: '0.25rem 0.6rem',
    borderRadius: 5,
    lineHeight: 1.4,
    flexShrink: 0,
    fontWeight: 600,
  },
  modalOverlay: {
    position: 'fixed' as const,
    inset: 0,
    background: 'rgba(0,0,0,0.65)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 9999,
  },
  modal: {
    background: '#0f172a',
    border: '1px solid #334155',
    borderRadius: 12,
    padding: '1.25rem 1.5rem',
    width: 340,
    maxWidth: '95vw',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 4,
  },
  modalLabel: {
    color: '#64748b',
    fontSize: '0.7rem',
    fontWeight: 700,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.06em',
    marginTop: 8,
    marginBottom: 3,
    display: 'block',
  },
  modalInput: {
    width: '100%',
    background: '#1e293b',
    border: '1px solid #334155',
    borderRadius: 6,
    color: '#f1f5f9',
    fontSize: '0.82rem',
    padding: '0.4rem 0.55rem',
    boxSizing: 'border-box' as const,
  },
  modalSaveBtn: {
    padding: '0.4rem 1rem',
    background: '#1d4ed8',
    color: '#fff',
    border: 'none',
    borderRadius: 7,
    cursor: 'pointer',
    fontSize: '0.8rem',
    fontWeight: 600,
  },
  modalCancelBtn: {
    padding: '0.4rem 0.8rem',
    background: '#1e293b',
    color: '#94a3b8',
    border: '1px solid #334155',
    borderRadius: 7,
    cursor: 'pointer',
    fontSize: '0.8rem',
  },
  spawnBtn: {
    background: '#1e3a5f',
    border: '1px solid #3b82f6',
    color: '#93c5fd',
    cursor: 'pointer',
    fontSize: '0.72rem',
    padding: '0.3rem 0.6rem',
    borderRadius: 5,
    fontWeight: 600,
    flex: 1,
  },
};
